### ISSUE TITLE
Play DRM-protected content securityLevel L1

### ISSUE THREAD

**Issue by TDUser91** [liuchuancong/better_player#1]
I'm unable to play content with top securityLevel L1:

you can try this media content from google exoplayer repo for L1: 

```
        "name": "HW secure all (L1)",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://proxy.uat.widevine.com/proxy?video_id=GTS_HW_SECURE_ALL&provider=widevine_test"
```

I tried it on Emulator as well as real devices and they both fail to play the content.

**Comment by liuchuancong** [comment]
You can use videoFormat
```
FORMAT_SS -> C.CONTENT_TYPE_SS
                FORMAT_DASH -> C.CONTENT_TYPE_DASH
                FORMAT_HLS -> C.CONTENT_TYPE_HLS
                FORMAT_OTHER -> C.CONTENT_TYPE_OTHER
                FORMAT_RTSP -> C.CONTENT_TYPE_RTSP
```

**Comment by liuchuancong** [comment]
@TDUser91  In china, I can't to do this!  would you please feedback to (media)[https://github.com/androidx/media] ?

**Comment by liuchuancong** [comment]
```
try {
                                val mediaDrm = FrameworkMediaDrm.newInstance(uuid!!)
                                // Force L3.
                                mediaDrm.setPropertyString("securityLevel", "L3")
                                return@setUuidAndExoMediaDrmProvider mediaDrm
                            } catch (e: UnsupportedDrmException) {
                                return@setUuidAndExoMediaDrmProvider DummyExoMediaDrm()
                            }
```
Maybe is DummyExoMediaDrm error

**Comment by TDUser91** [comment]
@liuchuancong I've found the root of the issue. BetterPlayer doesn't work with Widevine L1/L2 because of textures. It uses VideoPlayer and the way VideoPlayer processes video is using textures in software level and in order to play L1 protected-content it has to be Hardware level. What I've found is that I have to use SurfaceView (You can read more here: (https://source.android.com/docs/core/graphics/architecture and https://medium.com/androiddevelopers/android-hdr-migrating-from-textureview-to-surfaceview-part-1-how-to-migrate-6bfd7f4b970e)

**Comment by liuchuancong** [comment]
after change i used  SurfaceView ,but has lots of bug,like black screen @TDUser91

**Comment by liuchuancong** [comment]
@TDUser91  https://github.com/liuchuancong/better_player/commit/1bfa2bdad01587ab9a860d3b6f1f8bc8a35f9d61

**Comment by liuchuancong** [comment]
@TDUser91 I don't konw how to fix this, then i must delete this change
