### ISSUE TITLE
Got this issue on media3

### ISSUE THREAD

**Issue by akbar607** [liuchuancong/better_player#10]
`e: /Users/akbarcp/Desktop/better_player/android/src/main/kotlin/com/alizda/better_player/BetterPlayer.kt: (34, 32): Unresolved reference: ffmpeg
e: /Users/akbarcp/Desktop/better_player/android/src/main/kotlin/com/alizda/better_player/BetterPlayer.kt: (35, 32): Unresolved reference: vp9
e: /Users/akbarcp/Desktop/better_player/android/src/main/kotlin/com/alizda/better_player/BetterPlayer.kt: (130, 25): Unresolved reference: FfmpegAudioRenderer
e: /Users/akbarcp/Desktop/better_player/android/src/main/kotlin/com/alizda/better_player/BetterPlayer.kt: (153, 25): Unresolved reference: LibvpxVideoRenderer
`

**Comment by liuchuancong** [comment]
@akbar607 use [gsy_video_player](https://github.com/liuchuancong/gsy_video_player) instead of [better_player](https://github.com/liuchuancong/better_player)
