### ISSUE TITLE
Session ID must be unique. ID=

### ISSUE THREAD

**Issue by heshesh2010** [liuchuancong/better_player#3]
E/flutter ( 7607): <asynchronous suspension>
E/flutter ( 7607): #2      MethodChannelVideoPlayer.create
method_channel_video_player.dart:39
E/flutter ( 7607): <asynchronous suspension>
E/flutter ( 7607): #3      VideoPlayerController._create
video_player.dart:202
E/flutter ( 7607): <asynchronous suspension>
E/flutter ( 7607):
I/VideoCapabilities( 7607): Unsupported profile 4 for video/mp4v-es
D/HostConnection( 7607): HostConnection::get() New Host Connection established 0xee5f1b70, tid 7782
D/HostConnection( 7607): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
D/EGL_emulation( 7607): eglCreateContext: 0xee5e04c0: maj 3 min 0 rcv 3
D/EGL_emulation( 7607): eglMakeCurrent: 0xee5e04c0: ver 3 0 (tinfo 0xa4eab810) (first time)
E/EGL_emulation( 7607): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E/EGL_emulation( 7607): tid 7782: eglQueryContext(2019): error 0x3004 (EGL_BAD_ATTRIBUTE)
I/OMXClient( 7607): IOmx service obtained
D/SurfaceUtils( 7607): connecting to surface 0xe8f7d668, reason connectToSurface
I/MediaCodec( 7607): [OMX.google.hevc.decoder] setting surface generation to 7789569
D/SurfaceUtils( 7607): disconnecting from surface 0xe8f7d668, reason connectToSurface(reconnect)
D/SurfaceUtils( 7607): connecting to surface 0xe8f7d668, reason connectToSurface(reconnect)
E/ACodec  ( 7607): [OMX.google.hevc.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/ACodec  ( 7607): codec does not support config priority (err -1010)
D/CCodec  ( 7607): allocate(c2.android.aac.decoder)
I/Codec2Client( 7607): Available Codec2 services: "software"
I/CCodec  ( 7607): Created component [c2.android.aac.decoder]
D/CCodecConfig( 7607): read media type: audio/mp4a-latm

**Comment by liuchuancong** [comment]
pull andd try again!

**Comment by heshesh2010** [comment]
fixed thank you very much
