### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by heshesh2010** [liuchuancong/better_player#4]
Hi , 

I got this error when try to play some videos , and some other videos is working .

E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:593)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1544)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1163)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:1029)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:849)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:974)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1079)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:529)
E/MediaCodecVideoRenderer( 8266):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/MediaCodecVideoRenderer( 8266):       at android.os.Looper.loopOnce(Looper.java:226)
E/MediaCodecVideoRenderer( 8266):       at android.os.Looper.loop(Looper.java:313)
E/MediaCodecVideoRenderer( 8266):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/MediaCodecVideoRenderer( 8266):   Caused by: android.media.MediaCodec$CodecException: start failed
E/MediaCodecVideoRenderer( 8266):       at android.media.MediaCodec.native_start(Native Method)
E/MediaCodecVideoRenderer( 8266):       at android.media.MediaCodec.start(MediaCodec.java:2322)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:160)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:113)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1179)
E/MediaCodecVideoRenderer( 8266):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1087)
E/MediaCodecVideoRenderer( 8266):       ... 12 more

**Comment by liuchuancong** [comment]
So far, there will still be a lot of bugs about exoplayer

**Comment by liuchuancong** [comment]
If you don't konw what the url extension,the videoplayer use default ```ProgressiveMediaSource.Factory```.
In my case,i got extension with ```.php?xxx=xxx```
I use the code with 
```
mobileController?.setResolution(datasource,
        videoFormat: BetterPlayerVideoFormat.hls);
        mobileController?.play();
```
```
  dynamic mobileStateListener(BetterPlayerEvent state) {
    if (mobileController?.videoPlayerController != null) {
      if (state.betterPlayerEventType == BetterPlayerEventType.exception) {
        debounceListen(() {
          if(mobileController!.videoPlayerController!.value.errorDescription != null){
             if (mobileController!.videoPlayerController!.value.errorDescription! .contains('Source error') && room.platform == 'iptv' && !isTryToHls) {
              tryToHlsPlay();
            }else{
              hasError.value =
                mobileController?.videoPlayerController?.value.hasError ?? true;
            }
          }
        }, 1000);
      }
      isPlaying.value = mobileController?.isPlaying() ?? false;
      isBuffering.value = mobileController?.isBuffering() ?? false;
      isPipMode.value =
          mobileController?.videoPlayerController?.value.isPip ?? false;
    }
  }
```

Of cause,you can loop all of BetterPlayerVideoFormat
